#!/usr/bin/env python3
"""Tally PyPI and jsDelivr downloads and refresh the profile badge.

Data sources, in order of preference
------------------------------------
PyPI (all-time)
    1. pepy v2 API -- ``https://api.pepy.tech/api/v2/projects/{pkg}`` with an
       ``X-Api-Key`` header. Exact counts. Requires the ``PEPY_API_KEY``
       secret; pepy retired its keyless endpoint (it now returns 403).
    2. shields.io ``/pepy/dt/{pkg}`` -- the same endpoint the per-package
       badges in this README already use. No key needed, but the figure is
       rounded ("12.3k"), so the total is approximate.

jsDelivr
    shields.io ``/jsdelivr/gh/{period}/{owner}/{repo}``. jsDelivr publishes
    period-based stats only (hour/day/week/month/year), so the default
    period is ``hy`` = last 12 months. There is no all-time jsDelivr figure.

Safety
------
A failed fetch never overwrites the badge. The badge is only rewritten when
at least one source returned a number, and never to a value lower than the
one already published (download totals are monotonically increasing, so a
drop means we are looking at partial data).

Usage::

    python3 scripts/update-download-badges.py --readme profile/README.md
    python3 scripts/update-download-badges.py --dry-run
"""

from __future__ import annotations

import argparse
import gzip
import json
import os
import re
import sys
import urllib.error
import urllib.request

# --- what gets counted -------------------------------------------------------

PYPI_PACKAGES = [
    "qrforge",
    "localsitemap",
    "pyautoplot",
    "valx",
    "hued",
    "deepdefend",
    "codesafe",
    "pywebscrapr",
    "funcprofiler",
    "duplipy",
]

JSDELIVR_GH = [
    "infinitode/blurjs",
    # "johanbeytell1/alloy",  # uncomment once it is served through jsDelivr
]

# hy = hits per year, the longest window jsDelivr exposes.
JSDELIVR_PERIOD = "hy"

PEPY_V2 = "https://api.pepy.tech/api/v2/projects/{pkg}"
SHIELDS_PYPI = "https://img.shields.io/pepy/dt/{pkg}"
SHIELDS_JSDELIVR = "https://img.shields.io/jsdelivr/gh/{period}/{repo}"

# A new total this far below the published one counts as partial data and is
# refused. 5% absorbs display rounding while still catching a missing source
# (dropping one of eleven sources moves the total by ~9%).
DROP_TOLERANCE = 0.05

# Keys that hold an all-time count, highest confidence first.
COUNT_KEYS = ("total_downloads", "totaldownloads", "totalhits", "downloads", "hits")

START_RE = re.compile(
    r"<!--\s*TOTAL-DOWNLOADS:START[^\n]*\n.*?<!--\s*TOTAL-DOWNLOADS:END\s*-->", re.S
)
START_MARK = "<!-- TOTAL-DOWNLOADS:START (generated by scripts/update-download-badges.py) -->"
END_MARK = "<!-- TOTAL-DOWNLOADS:END -->"
BADGE = "![Total Downloads](https://img.shields.io/badge/Total%20Downloads-{value}-5d17eb)"
BADGE_VALUE_RE = re.compile(r"Total%20Downloads-([0-9][0-9.,]*)([kMB]?)-")
ANCHOR = "![](https://komarev.com/ghpvc/?username=infinitode&color=5d17eb)"

TEXT_RE = re.compile(r"<text[^>]*>([^<]*)</text>")
SHIELDS_VALUE_RE = re.compile(r"^([0-9][0-9.,]*)\s*([kMB]?)$")
_SUFFIX = {"": 1, "k": 1_000, "M": 1_000_000, "B": 1_000_000_000}


# --- network (the only I/O in this module) -----------------------------------


def fetch(url, headers=None, timeout=30):
    """Return ``(body_bytes, content_type)`` for *url*."""
    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": "Infinitode-download-badge/1.0",
            "Accept": "application/json, image/svg+xml, */*",
            **(headers or {}),
        },
    )
    with urllib.request.urlopen(request, timeout=timeout) as response:
        body = response.read()
        if response.headers.get("Content-Encoding", "").lower() == "gzip":
            body = gzip.decompress(body)
        return body, (response.headers.get("Content-Type") or "")


def fetch_json(url, headers=None, timeout=30):
    return json.loads(fetch(url, headers, timeout)[0].decode("utf-8"))


def fetch_text(url, headers=None, timeout=30):
    return fetch(url, headers, timeout)[0].decode("utf-8", "replace")


# --- parsers (pure) ----------------------------------------------------------


def _search(node, key):
    """Depth-first search for the first numeric value stored under *key*."""
    if isinstance(node, dict):
        for name, value in node.items():
            if name.lower() == key and isinstance(value, (int, float)) and not isinstance(value, bool):
                return value
        for value in node.values():
            found = _search(value, key)
            if found is not None:
                return found
    elif isinstance(node, list):
        for item in node:
            found = _search(item, key)
            if found is not None:
                return found
    return None


def find_count(payload):
    """Return the first all-time count found anywhere in a decoded payload."""
    for key in COUNT_KEYS:
        value = _search(payload, key)
        if value is not None:
            return int(value)
    return None


def parse_shields_badge(svg):
    """Pull the numeric value out of a shields.io SVG.

    shields.io renders the value as the last ``<text>`` element. Error badges
    ("unavailable", "no longer available") hold no number and yield ``None``.
    """
    for text in reversed([t.strip() for t in TEXT_RE.findall(svg or "")]):
        match = SHIELDS_VALUE_RE.match(text)
        if match:
            number = float(match.group(1).replace(",", ""))
            return int(round(number * _SUFFIX[match.group(2)]))
    return None


def format_count(total):
    """Compact, URL-safe badge value: 1234567 -> '1.23M', 45678 -> '45.7k'."""
    if total >= 1_000_000_000:
        return f"{total / 1e9:.2f}B"
    if total >= 999_950:  # 999_999 would render as the ugly "1000.0k"
        return f"{total / 1e6:.2f}M"
    if total >= 1_000:
        return f"{total / 1e3:.1f}k"
    return str(total)


def parse_badge_value(text):
    """Read the number currently published in the badge, or ``None``."""
    match = BADGE_VALUE_RE.search(text or "")
    if not match:
        return None
    return int(round(float(match.group(1).replace(",", "")) * _SUFFIX[match.group(2)]))


# --- source lookups ----------------------------------------------------------


def pypi_totals(packages, api_key=None, fetch_json=None, fetch_text=None):
    """All-time PyPI downloads per package. Exact with a key, rounded without."""
    # resolved here, not as a default argument, so the layer stays patchable
    fetch_json = fetch_json or globals()["fetch_json"]
    fetch_text = fetch_text or globals()["fetch_text"]
    totals, failures, notes = {}, {}, []
    for package in packages:
        errors = []
        count = None
        if api_key:
            try:
                payload = fetch_json(PEPY_V2.format(pkg=package), {"X-Api-Key": api_key})
                count = find_count(payload)
            except (urllib.error.URLError, ValueError) as error:
                errors.append(f"pepy v2 -> {error}")
            if count is None and not errors:
                errors.append("pepy v2 -> no total_downloads in response")
        else:
            notes.append("PEPY_API_KEY not set; using rounded shields.io figures for PyPI")
        if count is None:  # keyless fallback (or the keyed call failed)
            try:
                count = parse_shields_badge(fetch_text(SHIELDS_PYPI.format(pkg=package)))
            except (urllib.error.URLError, ValueError) as error:
                errors.append(f"shields.io -> {error}")
            if count is None and not any("shields.io" in e for e in errors):
                errors.append("shields.io -> no numeric value in badge")
        if count is not None:
            totals[package] = count
        else:
            failures[package] = "; ".join(errors) or "unknown error"
    return totals, failures, sorted(set(notes))


def jsdelivr_totals(repos, period=JSDELIVR_PERIOD, fetch_text=None):
    """jsDelivr hits per repo for *period* (default: last 12 months)."""
    fetch_text = fetch_text or globals()["fetch_text"]
    totals, failures = {}, {}
    for repo in repos:
        url = SHIELDS_JSDELIVR.format(period=period, repo=repo)
        try:
            count = parse_shields_badge(fetch_text(url))
        except (urllib.error.URLError, ValueError) as error:
            failures[repo] = f"{url} -> {error}"
            continue
        if count is None:
            failures[repo] = f"{url} -> no numeric value in badge"
            continue
        totals[repo] = count
    return totals, failures


def collect(api_key=None, fetch_json=None, fetch_text=None):
    fetch_json = fetch_json or globals()["fetch_json"]
    fetch_text = fetch_text or globals()["fetch_text"]
    pypi, pypi_failures, notes = pypi_totals(
        PYPI_PACKAGES, api_key=api_key, fetch_json=fetch_json, fetch_text=fetch_text
    )
    jsdelivr, jsdelivr_failures = jsdelivr_totals(JSDELIVR_GH, fetch_text=fetch_text)
    return {
        "pypi": pypi,
        "jsdelivr": jsdelivr,
        "failures": {**pypi_failures, **jsdelivr_failures},
        "notes": notes,
        "sources": len(pypi) + len(jsdelivr),
        "total": sum(pypi.values()) + sum(jsdelivr.values()),
    }


# --- README rewrite ----------------------------------------------------------


def render_block(total):
    return f"{START_MARK}\n{BADGE.format(value=format_count(total))}\n{END_MARK}"


def update_readme(text, total):
    """Replace (or insert) the badge block. Returns ``(new_text, changed)``."""
    block = render_block(total)
    if START_RE.search(text):
        new_text, _ = START_RE.subn(lambda _match: block, text, count=1)
        return new_text, new_text != text
    if ANCHOR in text:  # first run: drop the badge under the visitor counter
        return text.replace(ANCHOR, f"{ANCHOR}\n{block}", 1), True
    return text, False


# --- entry point -------------------------------------------------------------


def main(argv=None):
    parser = argparse.ArgumentParser(description="Refresh the total downloads badge.")
    parser.add_argument("--readme", default="profile/README.md")
    parser.add_argument("--dry-run", action="store_true", help="print the result, change nothing")
    parser.add_argument(
        "--allow-decrease",
        action="store_true",
        help="write the total even if it is lower than the published one",
    )
    args = parser.parse_args(argv)

    result = collect(api_key=os.environ.get("PEPY_API_KEY"))

    for note in result["notes"]:
        print(f"  note     {note}")
    for name, count in sorted(result["pypi"].items()):
        print(f"  pypi     {name:<20} {count:>14,}")
    for name, count in sorted(result["jsdelivr"].items()):
        print(f"  jsdelivr {name:<29} {count:>14,}")
    for name, reason in sorted(result["failures"].items()):
        print(f"  FAILED   {name}: {reason}", file=sys.stderr)
    print(f"  {'TOTAL':<38} {result['total']:>14,}  ({format_count(result['total'])})")

    # Never publish a number we could not actually measure.
    if result["sources"] == 0:
        print("Every source failed; the badge is left untouched.", file=sys.stderr)
        return 1

    with open(args.readme, encoding="utf-8") as handle:
        original = handle.read()

    published = parse_badge_value(original)
    # A published 0 is a leftover from a failed run, not a real measurement.
    # Allow for display rounding: "5.17M" can stand for anything in
    # [5,165,000, 5,175,000), so a tiny apparent drop is noise, not data loss.
    if (
        published
        and result["total"] < published * (1 - DROP_TOLERANCE)
        and not args.allow_decrease
    ):
        print(
            f"Refusing to publish {result['total']:,} over {published:,} "
            f"(more than {DROP_TOLERANCE:.0%} below the published figure; looks like "
            "partial data -- pass --allow-decrease to override).",
            file=sys.stderr,
        )
        return 0

    if args.dry_run:
        print("--dry-run: README left untouched")
        return 0

    updated, changed = update_readme(original, result["total"])
    if not changed:
        print(f"Badge already up to date in {args.readme}.")
        return 0

    with open(args.readme, "w", encoding="utf-8") as handle:
        handle.write(updated)
    print(f"Updated the badge in {args.readme}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
