#!/usr/bin/env python3
"""Tally all-time PyPI and jsDelivr downloads and refresh the profile badge.

Sums the all-time download counts for every package/repo listed below, then
rewrites the badge that sits between the ``TOTAL-DOWNLOADS`` markers in
``profile/README.md``.

All network access goes through :func:`fetch_json`, so the parsing, summing and
README-rewriting logic can be exercised offline by passing a custom fetcher.

Usage::

    python3 scripts/update-download-badges.py --readme profile/README.md
    python3 scripts/update-download-badges.py --dry-run          # print, don't write
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request

# --- what gets counted -------------------------------------------------------

PYPI_PACKAGES = [
    "qrforge",
    "localsitemap",
    "pyautoplot",
    "valx",
    "hued",
    "deepdefend",
    "codesafe",
    "pywebscrapr",
    "funcprofiler",
    "duplipy",
]

JSDELIVR_GH = [
    "infinitode/blurjs",
    # "johanbeytell1/alloy",  # uncomment once it is served through jsDelivr
]

# (url template, requires an API key)
PEPY_ENDPOINTS = [
    ("https://api.pepy.tech/api/v2/projects/{pkg}", True),
    ("https://api.pepy.tech/api/projects/{pkg}", False),  # legacy, keyless
]

JSDELIVR_ENDPOINTS = [
    "https://data.jsdelivr.com/v1/packages/gh/{repo}",
    "https://data.jsdelivr.com/v1/package/gh/{repo}",
]

# Keys that hold an *all-time* count, highest confidence first.
COUNT_KEYS = (
    "total_downloads",
    "totaldownloads",
    "totalhits",
    "downloads",
    "hits",
)

START_RE = re.compile(r"<!--\s*TOTAL-DOWNLOADS:START[^\n]*\n.*?<!--\s*TOTAL-DOWNLOADS:END\s*-->", re.S)
START_MARK = "<!-- TOTAL-DOWNLOADS:START (generated by scripts/update-download-badges.py) -->"
END_MARK = "<!-- TOTAL-DOWNLOADS:END -->"
BADGE = "![Total Downloads](https://img.shields.io/badge/Total%20Downloads-{value}-5d17eb)"
ANCHOR = "![](https://komarev.com/ghpvc/?username=infinitode&color=5d17eb)"


# --- network -----------------------------------------------------------------


def fetch_json(url, headers=None, timeout=30):
    """Fetch *url* and decode it as JSON. The only network call in this module."""
    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": "Infinitode-download-badge",
            "Accept": "application/json",
            **(headers or {}),
        },
    )
    with urllib.request.urlopen(request, timeout=timeout) as response:
        return json.loads(response.read().decode("utf-8"))


# --- pure logic --------------------------------------------------------------


def _search(node, key):
    """Depth-first search for the first numeric value stored under *key*."""
    if isinstance(node, dict):
        for name, value in node.items():
            if name.lower() == key and isinstance(value, (int, float)) and not isinstance(value, bool):
                return value
        for value in node.values():
            found = _search(value, key)
            if found is not None:
                return found
    elif isinstance(node, list):
        for item in node:
            found = _search(item, key)
            if found is not None:
                return found
    return None


def find_count(payload):
    """Return the first all-time count found anywhere in a decoded payload."""
    for key in COUNT_KEYS:
        value = _search(payload, key)
        if value is not None:
            return int(value)
    return None


def first_count(urls, fetcher=None, label=""):
    """Try each URL in turn and return the first count that comes back."""
    fetcher = fetcher or fetch_json  # resolved here so it stays patchable
    errors = []
    for url in urls:
        try:
            count = find_count(fetcher(url, None))
        except (urllib.error.URLError, ValueError) as error:
            errors.append(f"{url} -> {error}")
            continue
        if count is not None:
            return count, url
    raise LookupError(f"no download count for {label}: " + "; ".join(errors))


def pypi_totals(packages, api_key=None, fetcher=None):
    """All-time download count per PyPI package."""
    fetcher = fetcher or fetch_json
    totals, failures = {}, {}
    for package in packages:
        candidates = []
        for template, needs_key in PEPY_ENDPOINTS:
            if needs_key and not api_key:
                continue  # skip the keyless-incompatible endpoint
            candidates.append(
                (template.format(pkg=package), {"X-Api-Key": api_key} if needs_key else None)
            )
        errors = []
        for url, headers in candidates:
            try:
                count = find_count(fetcher(url, headers))
            except (urllib.error.URLError, ValueError) as error:
                errors.append(f"{url} -> {error}")
                continue
            if count is not None:
                totals[package] = count
                break
        else:
            failures[package] = f"no download count: " + "; ".join(errors)
    return totals, failures


def jsdelivr_totals(repos, fetcher=None):
    """All-time hit count per jsDelivr-served GitHub repo."""
    fetcher = fetcher or fetch_json
    totals, failures = {}, {}
    for repo in repos:
        urls = [template.format(repo=repo) for template in JSDELIVR_ENDPOINTS]
        try:
            totals[repo], _ = first_count(urls, fetcher, label=repo)
        except LookupError as error:
            failures[repo] = str(error)
    return totals, failures


def format_count(total):
    """Compact, URL-safe badge value: 1234567 -> '1.23M', 45678 -> '45.7k'."""
    if total >= 1_000_000:
        return f"{total / 1_000_000:.2f}M"
    if total >= 1_000:
        return f"{total / 1_000:.1f}k"
    return str(total)


def render_block(total):
    return f"{START_MARK}\n{BADGE.format(value=format_count(total))}\n{END_MARK}"


def update_readme(text, total):
    """Replace (or insert) the badge block. Returns ``(new_text, changed)``."""
    block = render_block(total)
    if START_RE.search(text):
        new_text, replacements = START_RE.subn(lambda _match: block, text, count=1)
        return new_text, new_text != text
    if ANCHOR in text:  # first run: drop the badge under the visitor counter
        return text.replace(ANCHOR, f"{ANCHOR}\n{block}", 1), True
    return text, False


# --- entry point -------------------------------------------------------------


def collect(fetcher=None, api_key=None):
    pypi, pypi_failures = pypi_totals(PYPI_PACKAGES, api_key=api_key, fetcher=fetcher)
    jsdelivr, jsdelivr_failures = jsdelivr_totals(JSDELIVR_GH, fetcher=fetcher)
    return {
        "pypi": pypi,
        "jsdelivr": jsdelivr,
        "failures": {**pypi_failures, **jsdelivr_failures},
        "total": sum(pypi.values()) + sum(jsdelivr.values()),
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--readme", default="profile/README.md")
    parser.add_argument("--dry-run", action="store_true", help="print the result, change nothing")
    args = parser.parse_args(argv)

    result = collect(api_key=os.environ.get("PEPY_API_KEY"))
    total = result["total"]

    for name, count in sorted(result["pypi"].items()):
        print(f"  pypi     {name:<16} {count:>12,}")
    for name, count in sorted(result["jsdelivr"].items()):
        print(f"  jsdelivr {name:<25} {count:>12,}")
    for name, reason in sorted(result["failures"].items()):
        print(f"  FAILED   {name}: {reason}", file=sys.stderr)
    print(f"  {'TOTAL':<33} {total:>12,}  ({format_count(total)})")

    if args.dry_run:
        print("\n--dry-run: README left untouched")
        return 0 if not result["failures"] else 1

    with open(args.readme, encoding="utf-8") as handle:
        original = handle.read()

    updated, changed = update_readme(original, total)
    if not changed:
        print(f"Badge already up to date in {args.readme}.")
        return 0 if not result["failures"] else 1

    with open(args.readme, "w", encoding="utf-8") as handle:
        handle.write(updated)
    print(f"Updated the badge in {args.readme}.")
    return 0 if not result["failures"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
